---
- include_role:
    name: admin_oc_login

- name: Create GitOps Namespace
  kubernetes.core.k8s:
    host: "https://api.{{ cluster_address }}:{{ k8s_port }}"
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: openshift-gitops-operator

- name: Create GitOps Operator Group
  kubernetes.core.k8s:
    host: "https://api.{{ cluster_address }}:{{ k8s_port }}"
    state: "{{ state }}"
    definition:
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: openshift-gitops-operator
        namespace: openshift-gitops-operator
      spec:
        upgradeStrategy: Default

- name: Create GitOps Operator Subscription
  kubernetes.core.k8s:
    host: "https://api.{{ cluster_address }}:{{ k8s_port }}"
    state: "{{ state }}"
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: openshift-gitops-operator
        namespace: openshift-gitops-operator
      spec:
        channel: gitops-1.15
        installPlanApproval: Automatic
        name: openshift-gitops-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace

- name: Wait for ArgoCD instance to become available
  kubernetes.core.k8s_info:
    host: "https://api.{{ cluster_address }}:{{ k8s_port }}"
    kind: ArgoCD
    name: openshift-gitops
    wait: true
    wait_condition:
      type: Available
    wait_sleep: 3