---
# Call ansible-for-openshift playbooks

- include_role:
    name: "{{ repos_path }}/ansible-for-openshift/playbooks/ocp/roles/aws_provision_ocp_ipi"
  vars:
    cluster_name: "{{ ocp_cluster.name }}"
    base_domain: "{{ ocp_cluster.base_domain }}"
...