---
- name: Perform OCP EUS Cluster Upgrade from 4.14 to 4.16
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: Beginning cluster upgrade process...

- name: Provision Cluster
  ansible.builtin.import_playbook: eus-upgrade-414-to-415.yaml

- name: Perform Day 2 Configuration
  ansible.builtin.import_playbook: eus-upgrade-415-to-416.yaml